In [1]:
import pandas as pd
import numpy as np
import re

In [ ]:
pd.set_option("display.max_columns", None)

In [ ]:
df = pd.read_csv("data/hakaton.csv", sep=";")
df

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
0,МУСЮС,АЛЕКСАНДР,NaN,2013-07-16,М,240045105,АГАФОНОВА,КЛАВДИЯ,NaN,1987-07-06,Ж,106077198701603,26-11-60078-000038-4,1022402487304,муниципальное автономное общеобразовательное у...,1142452001130,краевое бюджетное общеобразовательное учрежден...,20611,6,2026-02-25,Недостаточный
1,СОБОЛЕВ,ЮРИЙ,ГЕННАДЬЕВИЧ,2018-01-26,М,-1236233,КАБЛИН,ВАЛЕНТИН,ГЕННАДИЕВИЧ,1991-03-15,М,1571302,25-11-70122-000036-6,1025007390077,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,1035004258970,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,120126,1,2025-12-16,Недостаточный
2,РЯБОВ,ГЕННАДИЙ,СЕРГЕЕВИЧ,2014-08-21,М,5974549,ЗАКИРОВ,БОРИС,СЕРГЕЕВИЧ,1990-03-07,М,5480835,26-11-70285-000004-4,1037816029393,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ ...,1037816029547,Государственное бюджетное общеобразовательное ...,10410,4,2026-01-20,Достаточный
3,БОРИСОВ,АНАТОЛИЙ,НИКОЛЛАЕВИЧ,2018-07-22,М,3702355,ДЖАЛОЛОВ,ЕВГЕНИЙ,АНДРАНИКОВИЧ,1992-08-23,М,402238324,26-11-70046-000006-7,1021603470360,Муниципальное бюджетное общеобразовательное уч...,1241600037315,Муниципальное бюджетное общеобразовательное уч...,20133,1,2026-02-04,Недостаточный
4,КАРПЕВИЧ,ВИКТОР,ЮРЬЕВИЧ,2019-01-18,М,0000000,ШАПРАН,ЕЛЕНА,ПАВЛОВНА,1995-01-17,Ж,0352905,25-11-60108-000020-9,1023402988234,муниципальное общеобразовательное учреждение С...,1023402982173,"муниципальное общеобразовательное учреждение ""...",60105,1,2025-06-10,достаточный
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25623,ЛАЗАРЕВ,ДЕНИС,ВЛАДИМИРОВИЧ,2015-06-28,М,2118425,ЛАЗАРЕВ,ВАЛЕРИЙ,ПЕТРОВИЧ,1991-10-06,М,402450094,25-11-70289-000015-7,1022701291250,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,60304,3,2025-07-14,Недостаточный
25624,ВИДАКОВ,МИХАИЛ,СЕРГЕЕВИЧ,2018-03-06,М,010080310,КРАСНОКУТСКИЙ,ИЛЬЯ,ВЛАДИМИРОВИЧ,1991-11-07,М,4127610,25-11-70289-000009-8,1022701286508,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,80110,1,2025-08-27,Недостаточный
25625,ТОЛОКОНУШКОВ,ЕВГЕНИЙ,ФЕДОРОВИЧ,2018-04-14,М,-N0849879,ВАСИЛЕНКО,БОРИС,СЕРГЕЕВИЧ,1978-10-02,М,2920197,25-11-70289-000014-8,1022701283208,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,80109,1,2025-08-27,Достаточный
25626,ТИХОНОВ,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,2017-09-11,М,21109201751729,МИРЗОЯН,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,1987-05-17,М,3196439,25-11-70289-000019-9,1022701291250,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,90114,1,2025-09-25,Недостаточный
25627,СОРОКИН,НИКОЛАЙ,НИКОЛАЕВИЧ,2010-01-23,М,8954785,СОРОКИН,ГРИГОРИЙ,ВЛАДИМИРОВИЧ,1978-06-24,М,845120184,25-11-70284-000634-1,1037739385056,Государственное бюджетное общеобразовательное ...,1115074013130,Государственное бюджетное общеобразовательное ...,50802,8,2025-05-07,Недостаточный

In [ ]:
df["result"] = df["result"].str.strip().str.upper()

cols_content = [c for c in df.columns if c not in ["our_number", "name_naprav", "name_area"]]
before = len(df)
df = df.drop_duplicates(subset=cols_content, keep="first")
df

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
0,МУСЮС,АЛЕКСАНДР,NaN,2013-07-16,М,240045105,АГАФОНОВА,КЛАВДИЯ,NaN,1987-07-06,Ж,106077198701603,26-11-60078-000038-4,1022402487304,муниципальное автономное общеобразовательное у...,1142452001130,краевое бюджетное общеобразовательное учрежден...,20611,6,2026-02-25,НЕДОСТАТОЧНЫЙ
1,СОБОЛЕВ,ЮРИЙ,ГЕННАДЬЕВИЧ,2018-01-26,М,-1236233,КАБЛИН,ВАЛЕНТИН,ГЕННАДИЕВИЧ,1991-03-15,М,1571302,25-11-70122-000036-6,1025007390077,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,1035004258970,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,120126,1,2025-12-16,НЕДОСТАТОЧНЫЙ
2,РЯБОВ,ГЕННАДИЙ,СЕРГЕЕВИЧ,2014-08-21,М,5974549,ЗАКИРОВ,БОРИС,СЕРГЕЕВИЧ,1990-03-07,М,5480835,26-11-70285-000004-4,1037816029393,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ ...,1037816029547,Государственное бюджетное общеобразовательное ...,10410,4,2026-01-20,ДОСТАТОЧНЫЙ
3,БОРИСОВ,АНАТОЛИЙ,НИКОЛЛАЕВИЧ,2018-07-22,М,3702355,ДЖАЛОЛОВ,ЕВГЕНИЙ,АНДРАНИКОВИЧ,1992-08-23,М,402238324,26-11-70046-000006-7,1021603470360,Муниципальное бюджетное общеобразовательное уч...,1241600037315,Муниципальное бюджетное общеобразовательное уч...,20133,1,2026-02-04,НЕДОСТАТОЧНЫЙ
4,КАРПЕВИЧ,ВИКТОР,ЮРЬЕВИЧ,2019-01-18,М,0000000,ШАПРАН,ЕЛЕНА,ПАВЛОВНА,1995-01-17,Ж,0352905,25-11-60108-000020-9,1023402988234,муниципальное общеобразовательное учреждение С...,1023402982173,"муниципальное общеобразовательное учреждение ""...",60105,1,2025-06-10,ДОСТАТОЧНЫЙ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25623,ЛАЗАРЕВ,ДЕНИС,ВЛАДИМИРОВИЧ,2015-06-28,М,2118425,ЛАЗАРЕВ,ВАЛЕРИЙ,ПЕТРОВИЧ,1991-10-06,М,402450094,25-11-70289-000015-7,1022701291250,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,60304,3,2025-07-14,НЕДОСТАТОЧНЫЙ
25624,ВИДАКОВ,МИХАИЛ,СЕРГЕЕВИЧ,2018-03-06,М,010080310,КРАСНОКУТСКИЙ,ИЛЬЯ,ВЛАДИМИРОВИЧ,1991-11-07,М,4127610,25-11-70289-000009-8,1022701286508,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,80110,1,2025-08-27,НЕДОСТАТОЧНЫЙ
25625,ТОЛОКОНУШКОВ,ЕВГЕНИЙ,ФЕДОРОВИЧ,2018-04-14,М,-N0849879,ВАСИЛЕНКО,БОРИС,СЕРГЕЕВИЧ,1978-10-02,М,2920197,25-11-70289-000014-8,1022701283208,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,80109,1,2025-08-27,ДОСТАТОЧНЫЙ
25626,ТИХОНОВ,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,2017-09-11,М,21109201751729,МИРЗОЯН,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,1987-05-17,М,3196439,25-11-70289-000019-9,1022701291250,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,90114,1,2025-09-25,НЕДОСТАТОЧНЫЙ
25627,СОРОКИН,НИКОЛАЙ,НИКОЛАЕВИЧ,2010-01-23,М,8954785,СОРОКИН,ГРИГОРИЙ,ВЛАДИМИРОВИЧ,1978-06-24,М,845120184,25-11-70284-000634-1,1037739385056,Государственное бюджетное общеобразовательное ...,1115074013130,Государственное бюджетное общеобразовательное ...,50802,8,2025-05-07,НЕДОСТАТОЧНЫЙ

## пример неправильного ОГРН

In [ ]:
df["id_doc"] = df["id_doc"].replace("-", np.nan)
mask_valid = df["id_doc"].notna()

df_valid = df[mask_valid].copy()
df_invalid = df[~mask_valid].copy() 

before = len(df_valid)
df_valid = df_valid.sort_values(["id_doc", "test_date", "variant", "class", "result"])
df_valid = df_valid.drop_duplicates(subset=["id_doc", "test_date", "variant", "class"], keep="last")
print(f"  1b. Дубликаты по (id_doc, date, variant, class): {before - len(df_valid)}")

df = pd.concat([df_valid, df_invalid], ignore_index=True)

  1b. Дубликаты по (id_doc, date, variant, class): 80

In [ ]:
ogrn_bad = df[df["ogrn_naprav"].astype(str).str.len() != 13]
ogrn_bad

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
8747,ПАТАЛАХА,ТАТЬЯНА,АЛЕКСЕЕВНА,2016-12-10,Ж,1064712,УТОЧКИН,ВАЛЕРИЙ,ФЁДОРОВИЧ,1993-12-16,М,9305657,26-11-30544-000005-4,321057100012773,Индивидуальный предприниматель СУВАРОВА ГЮЛЬНА...,1020502000507,Муниципальное бюджетное общеобразовательное уч...,10129,1,2026-01-22,ДОСТАТОЧНЫЙ

In [ ]:
df[df["id_doc"] == "1064712"]

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
8747,ПАТАЛАХА,ТАТЬЯНА,АЛЕКСЕЕВНА,2016-12-10,Ж,1064712,УТОЧКИН,ВАЛЕРИЙ,ФЁДОРОВИЧ,1993-12-16,М,9305657,26-11-30544-000005-4,321057100012773,Индивидуальный предприниматель СУВАРОВА ГЮЛЬНА...,1020502000507,Муниципальное бюджетное общеобразовательное уч...,10129,1,2026-01-22,ДОСТАТОЧНЫЙ

In [ ]:
df[(df["last_name"] == "ПАТАЛАХА") & (df["first_name"] == "ТАТЬЯНА")]

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
8747,ПАТАЛАХА,ТАТЬЯНА,АЛЕКСЕЕВНА,2016-12-10,Ж,1064712,УТОЧКИН,ВАЛЕРИЙ,ФЁДОРОВИЧ,1993-12-16,М,9305657,26-11-30544-000005-4,321057100012773,Индивидуальный предприниматель СУВАРОВА ГЮЛЬНА...,1020502000507,Муниципальное бюджетное общеобразовательное уч...,10129,1,2026-01-22,ДОСТАТОЧНЫЙ

## пример теста до рождения

In [ ]:
for col in ["bdate", "test_date", "guard_bdate"]:
    df[col] = pd.to_datetime(df[col])

In [ ]:
test_before_birth = df["test_date"] < df["bdate"]
df[test_before_birth]

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
9624,ЛУКОНИН,МИХАИЛ,NaN,2025-09-18,М,13653549,ЛУКОНИН,АНАТОЛИЙ,НИКОЛАЕВИЧ,1982-06-13,М,4223444657,25-11-74682-000034-0,1183668037189,Муниципальное бюджетное общеобразовательное уч...,1193668014737,муниципальное бюджетное общеобразовательное уч...,90706,7,2025-09-16,НЕДОСТАТОЧНЫЙ

In [ ]:
df[df["id_doc"] == "13653549"]

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
9624,ЛУКОНИН,МИХАИЛ,NaN,2025-09-18,М,13653549,ЛУКОНИН,АНАТОЛИЙ,НИКОЛАЕВИЧ,1982-06-13,М,4223444657,25-11-74682-000034-0,1183668037189,Муниципальное бюджетное общеобразовательное уч...,1193668014737,муниципальное бюджетное общеобразовательное уч...,90706,7,2025-09-16,НЕДОСТАТОЧНЫЙ

In [ ]:
df[(df["last_name"] == "ЛУКОНИН") & (df["first_name"] == "МИХАИЛ")]

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
9624,ЛУКОНИН,МИХАИЛ,NaN,2025-09-18,М,13653549,ЛУКОНИН,АНАТОЛИЙ,НИКОЛАЕВИЧ,1982-06-13,М,4223444657,25-11-74682-000034-0,1183668037189,Муниципальное бюджетное общеобразовательное уч...,1193668014737,муниципальное бюджетное общеобразовательное уч...,90706,7,2025-09-16,НЕДОСТАТОЧНЫЙ
22996,ЛУКОНИН,МИХАИЛ,NaN,2012-09-18,М,N13653549,ЛУКОНИН,АНАТОЛИЙ,НИКОЛАЕВИЧ,1982-06-13,М,4223444657,25-11-74682-000076-9,1183668037189,Муниципальное бюджетное общеобразовательное уч...,1193668014737,муниципальное бюджетное общеобразовательное уч...,120709,7,2025-12-17,НЕДОСТАТОЧНЫЙ

Тут очевидно просто переприсвоим одной из строк значение

##