In [57]:
import pandas as pd
import numpy as np

In [ ]:
pd.set_option("display.max_columns", None)

In [ ]:
df = pd.read_csv("data/hakaton.csv", sep=";")
df

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
0,МУСЮС,АЛЕКСАНДР,NaN,2013-07-16,М,240045105,АГАФОНОВА,КЛАВДИЯ,NaN,1987-07-06,Ж,106077198701603,26-11-60078-000038-4,1022402487304,"муниципальное автономное общеобразовательное учреждение ""Средняя школа № 24 имени Героя Советского Союза М.В. Водопьянова""",1142452001130,"краевое бюджетное общеобразовательное учреждение ""Школа дистанционного образования""",20611,6,2026-02-25,Недостаточный
1,СОБОЛЕВ,ЮРИЙ,ГЕННАДЬЕВИЧ,2018-01-26,М,-1236233,КАБЛИН,ВАЛЕНТИН,ГЕННАДИЕВИЧ,1991-03-15,М,1571302,25-11-70122-000036-6,1025007390077,"МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ""ЛУХОВИЦКАЯ СРЕДНЯЯ ОБЩЕОБРАЗОВАТЕЛЬНАЯ ШКОЛА № 2""",1035004258970,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ СРЕДНЯЯ ОБЩЕОБРАЗОВАТЕЛЬНАЯ ШКОЛА № 17,120126,1,2025-12-16,Недостаточный
2,РЯБОВ,ГЕННАДИЙ,СЕРГЕЕВИЧ,2014-08-21,М,5974549,ЗАКИРОВ,БОРИС,СЕРГЕЕВИЧ,1990-03-07,М,5480835,26-11-70285-000004-4,1037816029393,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ СРЕДНЯЯ ОБЩЕОБРАЗОВАТЕЛЬНАЯ ШКОЛА № 141 КРАСНОГВАРДЕЙСКОГО РАЙОНА САНКТ-ПЕТЕРБУРГА,1037816029547,Государственное бюджетное общеобразовательное учреждение гимназия № 177 Красногвардейского района Санкт-Петербурга,10410,4,2026-01-20,Достаточный
3,БОРИСОВ,АНАТОЛИЙ,НИКОЛЛАЕВИЧ,2018-07-22,М,3702355,ДЖАЛОЛОВ,ЕВГЕНИЙ,АНДРАНИКОВИЧ,1992-08-23,М,402238324,26-11-70046-000006-7,1021603470360,Муниципальное бюджетное общеобразовательное учреждение Средняя общеобразовательная школа №127 Приволжского района г.Казани,1241600037315,Муниципальное бюджетное общеобразовательное учреждение «Многопрофильный лицей №133» Приволжского района г. Казани»,20133,1,2026-02-04,Недостаточный
4,КАРПЕВИЧ,ВИКТОР,ЮРЬЕВИЧ,2019-01-18,М,0000000,ШАПРАН,ЕЛЕНА,ПАВЛОВНА,1995-01-17,Ж,0352905,25-11-60108-000020-9,1023402988234,муниципальное общеобразовательное учреждение Средняя школа № 85 имени Героя Российской Федерации Г.П.Лячина Дзержинского района Волгограда,1023402982173,"муниципальное общеобразовательное учреждение ""Лицей № 8 ""Олимпия"" Дзержинского района Волгограда""",60105,1,2025-06-10,достаточный
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25623,ЛАЗАРЕВ,ДЕНИС,ВЛАДИМИРОВИЧ,2015-06-28,М,2118425,ЛАЗАРЕВ,ВАЛЕРИЙ,ПЕТРОВИЧ,1991-10-06,М,402450094,25-11-70289-000015-7,1022701291250,"муниципальное автономное общеобразовательное учреждение г. Хабаровска ""Многопрофильный лицей имени 202-ой воздушно-десантной бригады""",1022701289170,"муниципальное бюджетное общеобразовательное учреждение ""Средняя школа № 76 имени А.А. Есягина""",60304,3,2025-07-14,Недостаточный
25624,ВИДАКОВ,МИХАИЛ,СЕРГЕЕВИЧ,2018-03-06,М,010080310,КРАСНОКУТСКИЙ,ИЛЬЯ,ВЛАДИМИРОВИЧ,1991-11-07,М,4127610,25-11-70289-000009-8,1022701286508,муниципальное автономное общеобразовательное учреждение г. Хабаровска Средняя школа № 66,1022701289170,"муниципальное бюджетное общеобразовательное учреждение ""Средняя школа № 76 имени А.А. Есягина""",80110,1,2025-08-27,Недостаточный
25625,ТОЛОКОНУШКОВ,ЕВГЕНИЙ,ФЕДОРОВИЧ,2018-04-14,М,-N0849879,ВАСИЛЕНКО,БОРИС,СЕРГЕЕВИЧ,1978-10-02,М,2920197,25-11-70289-000014-8,1022701283208,муниципальное автономное общеобразовательное учреждение г. Хабаровска «Средняя школа № 47 имени Героя Российской Федерации Владимира Александровича Тамгина»,1022701289170,"муниципальное бюджетное общеобразовательное учреждение ""Средняя школа № 76 имени А.А. Есягина""",80109,1,2025-08-27,Достаточный
25626,ТИХОНОВ,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,2017-09-11,М,21109201751729,МИРЗОЯН,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,1987-05-17,М,3196439,25-11-70289-000019-9,1022701291250,"муниципальное автономное общеобразовательное учреждение г. Хабаровска ""Многопрофильный лицей имени 202-ой воздушно-десантной бригады""",1022701289170,"муниципальное бюджетное общеобразовательное учреждение ""Средняя школа № 76 имени А.А. Есягина""",90114,1,2025-09-25,Недостаточный
25627,СОРОКИН,НИКОЛАЙ,НИКОЛАЕВИЧ,2010-01-23,М,8954785,СОРОКИН,ГРИГОРИЙ,ВЛАДИМИРОВИЧ,1978-06-24,М,845120184,25-11-70284-000634-1,1037739385056,Государственное бюджетное общеобразовательное учреждение города Москвы «Школа № 37»,1115074013130,Государственное бюджетное общеобразовательное учреждение города Москвы «Школа № 2083»,50802,8,2025-05-07,Недостаточный

## Заполняем пропущенные id_doc

1. Мы выяснили, что есть N/a, и есть "-", превратим их в n/a

In [ ]:
df_id_full = df.copy()
df_id_full["id_doc"] = df_id_full["id_doc"].replace("-", np.nan)

In [ ]:
counts = df_id_full["id_doc"].value_counts()
counts

id_doc
0594160           9
0682253           8
404331516         8
0682384           6
0682366           6
                 ..
3984093           1
4508342           1
5540615           1
-N0849879         1
21109201751729    1
Name: count, Length: 21926, dtype: int64

In [62]:
df_id_full.isna().sum()

last_name               0
first_name              0
middle_name          4469
bdate                   0
gender                  0
id_doc                 46
guard_last_name         0
guard_first_name        0
guard_middle_name    7389
guard_bdate             0
guard_gender            0
guard_id_doc           76
our_number              0
ogrn_naprav             0
name_naprav             0
ogrn_area               0
name_area               0
variant                 0
class                   0
test_date               0
result                  0
dtype: int64

2. Теперь разделим датасет на два датафрейма:
- один будет с id_doc == na
- второй будет просто без них

In [ ]:
df_with_na = df_id_full[df_id_full["id_doc"].isna()]
df_with_na = df_with_na.reset_index(drop=True)

df_without_na = df_id_full[df_id_full["id_doc"].notna()]
df_without_na = df_without_na.reset_index(drop=True)

3. Сейчас надо сделать join между ними (?) по ФИО и по др

In [64]:
df_without_na

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
0,МУСЮС,АЛЕКСАНДР,NaN,2013-07-16,М,240045105,АГАФОНОВА,КЛАВДИЯ,NaN,1987-07-06,Ж,106077198701603,26-11-60078-000038-4,1022402487304,"муниципальное автономное общеобразовательное учреждение ""Средняя школа № 24 имени Героя Советского Союза М.В. Водопьянова""",1142452001130,"краевое бюджетное общеобразовательное учреждение ""Школа дистанционного образования""",20611,6,2026-02-25,Недостаточный
1,СОБОЛЕВ,ЮРИЙ,ГЕННАДЬЕВИЧ,2018-01-26,М,-1236233,КАБЛИН,ВАЛЕНТИН,ГЕННАДИЕВИЧ,1991-03-15,М,1571302,25-11-70122-000036-6,1025007390077,"МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ""ЛУХОВИЦКАЯ СРЕДНЯЯ ОБЩЕОБРАЗОВАТЕЛЬНАЯ ШКОЛА № 2""",1035004258970,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ СРЕДНЯЯ ОБЩЕОБРАЗОВАТЕЛЬНАЯ ШКОЛА № 17,120126,1,2025-12-16,Недостаточный
2,РЯБОВ,ГЕННАДИЙ,СЕРГЕЕВИЧ,2014-08-21,М,5974549,ЗАКИРОВ,БОРИС,СЕРГЕЕВИЧ,1990-03-07,М,5480835,26-11-70285-000004-4,1037816029393,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ СРЕДНЯЯ ОБЩЕОБРАЗОВАТЕЛЬНАЯ ШКОЛА № 141 КРАСНОГВАРДЕЙСКОГО РАЙОНА САНКТ-ПЕТЕРБУРГА,1037816029547,Государственное бюджетное общеобразовательное учреждение гимназия № 177 Красногвардейского района Санкт-Петербурга,10410,4,2026-01-20,Достаточный
3,БОРИСОВ,АНАТОЛИЙ,НИКОЛЛАЕВИЧ,2018-07-22,М,3702355,ДЖАЛОЛОВ,ЕВГЕНИЙ,АНДРАНИКОВИЧ,1992-08-23,М,402238324,26-11-70046-000006-7,1021603470360,Муниципальное бюджетное общеобразовательное учреждение Средняя общеобразовательная школа №127 Приволжского района г.Казани,1241600037315,Муниципальное бюджетное общеобразовательное учреждение «Многопрофильный лицей №133» Приволжского района г. Казани»,20133,1,2026-02-04,Недостаточный
4,КАРПЕВИЧ,ВИКТОР,ЮРЬЕВИЧ,2019-01-18,М,0000000,ШАПРАН,ЕЛЕНА,ПАВЛОВНА,1995-01-17,Ж,0352905,25-11-60108-000020-9,1023402988234,муниципальное общеобразовательное учреждение Средняя школа № 85 имени Героя Российской Федерации Г.П.Лячина Дзержинского района Волгограда,1023402982173,"муниципальное общеобразовательное учреждение ""Лицей № 8 ""Олимпия"" Дзержинского района Волгограда""",60105,1,2025-06-10,достаточный
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25577,ЛАЗАРЕВ,ДЕНИС,ВЛАДИМИРОВИЧ,2015-06-28,М,2118425,ЛАЗАРЕВ,ВАЛЕРИЙ,ПЕТРОВИЧ,1991-10-06,М,402450094,25-11-70289-000015-7,1022701291250,"муниципальное автономное общеобразовательное учреждение г. Хабаровска ""Многопрофильный лицей имени 202-ой воздушно-десантной бригады""",1022701289170,"муниципальное бюджетное общеобразовательное учреждение ""Средняя школа № 76 имени А.А. Есягина""",60304,3,2025-07-14,Недостаточный
25578,ВИДАКОВ,МИХАИЛ,СЕРГЕЕВИЧ,2018-03-06,М,010080310,КРАСНОКУТСКИЙ,ИЛЬЯ,ВЛАДИМИРОВИЧ,1991-11-07,М,4127610,25-11-70289-000009-8,1022701286508,муниципальное автономное общеобразовательное учреждение г. Хабаровска Средняя школа № 66,1022701289170,"муниципальное бюджетное общеобразовательное учреждение ""Средняя школа № 76 имени А.А. Есягина""",80110,1,2025-08-27,Недостаточный
25579,ТОЛОКОНУШКОВ,ЕВГЕНИЙ,ФЕДОРОВИЧ,2018-04-14,М,-N0849879,ВАСИЛЕНКО,БОРИС,СЕРГЕЕВИЧ,1978-10-02,М,2920197,25-11-70289-000014-8,1022701283208,муниципальное автономное общеобразовательное учреждение г. Хабаровска «Средняя школа № 47 имени Героя Российской Федерации Владимира Александровича Тамгина»,1022701289170,"муниципальное бюджетное общеобразовательное учреждение ""Средняя школа № 76 имени А.А. Есягина""",80109,1,2025-08-27,Достаточный
25580,ТИХОНОВ,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,2017-09-11,М,21109201751729,МИРЗОЯН,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,1987-05-17,М,3196439,25-11-70289-000019-9,1022701291250,"муниципальное автономное общеобразовательное учреждение г. Хабаровска ""Многопрофильный лицей имени 202-ой воздушно-десантной бригады""",1022701289170,"муниципальное бюджетное общеобразовательное учреждение ""Средняя школа № 76 имени А.А. Есягина""",90114,1,2025-09-25,Недостаточный
25581,СОРОКИН,НИКОЛАЙ,НИКОЛАЕВИЧ,2010-01-23,М,8954785,СОРОКИН,ГРИГОРИЙ,ВЛАДИМИРОВИЧ,1978-06-24,М,845120184,25-11-70284-000634-1,1037739385056,Государственное бюджетное общеобразовательное учреждение города Москвы «Школа № 37»,1115074013130,Государственное бюджетное общеобразовательное учреждение города Москвы «Школа № 2083»,50802,8,2025-05-07,Недостаточный

In [ ]:
dup = df_with_na.merge(df_without_na, "inner", on=["last_name", "first_name", "middle_name", "bdate"])

dup[["id_doc_x", "id_doc_y"]]

  id_doc_x  id_doc_y
0      NaN  -0416345
1      NaN   0682356
2      NaN   -846956
3      NaN   0682356
4      NaN    261113
5      NaN   0737210

In [66]:
dup

,last_name,first_name,middle_name,bdate,gender_x,id_doc_x,guard_last_name_x,guard_first_name_x,guard_middle_name_x,guard_bdate_x,guard_gender_x,guard_id_doc_x,our_number_x,ogrn_naprav_x,name_naprav_x,ogrn_area_x,name_area_x,variant_x,class_x,test_date_x,result_x,gender_y,id_doc_y,guard_last_name_y,guard_first_name_y,guard_middle_name_y,guard_bdate_y,guard_gender_y,guard_id_doc_y,our_number_y,ogrn_naprav_y,name_naprav_y,ogrn_area_y,name_area_y,variant_y,class_y,test_date_y,result_y
0,КЛИМОВ,ДЕНИС,СЕРГЕЕВИЧ,2011-11-29,М,NaN,ЮН,МАКСИМ,ВЛАДИМИРОВИЧ,1989-11-15,М,6761430,26-11-30858-000004-9,1026500527580,Муниципальное автономное общеобразовательное учреждение средняя общеобразовательная школа № 8 имени генерал-лейтенанта В.Г. Асапова города Южно-Сахалинска,1026500529769,Муниципальное автономное общеобразовательное учреждение средняя общеобразовательная школа № 5 г. Южно-Сахалинска,10810,8,2026-01-22,недостаточный,М,-0416345,ЮН,МАКСИМ,ВЛАДИМИРОВИЧ,1989-12-15,М,6761430,25-11-30858-000068-2,1026500527580,Муниципальное автономное общеобразовательное учреждение средняя общеобразовательная школа № 8 имени генерал-лейтенанта В.Г. Асапова города Южно-Сахалинска,1026500529769,Муниципальное автономное общеобразовательное учреждение средняя общеобразовательная школа № 5 г. Южно-Сахалинска,10807,8,2025-10-09,Недостаточный
1,КОШКИНА,АННА,МИХАЙЛОВНА,2014-09-17,Ж,NaN,КУДРЯВЦЕВА,НАТАЛЬЯ,НИКОЛАЕВНА,1985-04-10,Ж,NaN,25-11-10668-000003-7,1022901535843,"Муниципальное бюджетное общеобразовательное учреждение ""Октябрьская средняя общеобразовательная школа № 2""",1022901535843,"Муниципальное бюджетное общеобразовательное учреждение ""Октябрьская средняя общеобразовательная школа № 2""",120409,4,2025-12-11,Достаточный,Ж,0682356,СИЛАЕВ,АЛЕКСАНДР,ЕФИМОВИЧ,1985-09-05,М,0682318,25-11-70089-000038-8,1222900007483,"МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ГОРОДСКОГО ОКРУГА ""ГОРОД АРХАНГЕЛЬСК"" ""СРЕДНЯЯ ШКОЛА № 7 ИМЕНИ ВЛАДИМИРА НИКОЛАЕВИЧА БУЛАТОВА""",1022900530619,"муниципальное бюджетное общеобразовательное учреждение городского округа ""Город Архангельск"" ""Средняя школа № 28 имени Жореса Иванович Алфёрова""",80505,5,2025-08-22,Недостаточный
2,МИХАЙЛОВСКИЙ,АЛЕКСАНДР,АНАТОЛЬЕВИЧ,2018-10-04,М,NaN,ВИХРОВА,ЗИНАИДА,ИВАНОВНА,1991-02-19,Ж,0249074,25-11-70284-000555-3,1127747074751,Государственное бюджетное общеобразовательное учреждение города Москвы «Школа № 2000»,1115074013130,Государственное бюджетное общеобразовательное учреждение города Москвы «Школа № 2083»,110121,1,2025-11-26,Недостаточный,М,-846956,ВИХРОВА,ЗИНАИДА,ИВАНОВНА,1991-02-19,Ж,0249074,25-11-70284-000446-7,1127747074751,Государственное бюджетное общеобразовательное учреждение города Москвы «Школа № 2000»,1115074013130,Государственное бюджетное общеобразовательное учреждение города Москвы «Школа № 2083»,80109,1,2025-08-06,Недостаточный
3,КОШКИНА,ГАЛИНА,МИХАЙЛОВНА,2013-03-01,Ж,NaN,КУДРЯВЦЕВА,НАТАЛЬЯ,НИКОЛАЕВНА,1985-04-10,Ж,NaN,25-11-10668-000002-1,1022901535843,"Муниципальное бюджетное общеобразовательное учреждение ""Октябрьская средняя общеобразовательная школа № 2""",1022901535843,"Муниципальное бюджетное общеобразовательное учреждение ""Октябрьская средняя общеобразовательная школа № 2""",120409,4,2025-12-11,Достаточный,Ж,0682356,СИЛАЕВ,АЛЕКСАНДР,ЕФИМОВИЧ,1985-09-05,М,0682318,25-11-70089-000037-5,1222900007483,"МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ГОРОДСКОГО ОКРУГА ""ГОРОД АРХАНГЕЛЬСК"" ""СРЕДНЯЯ ШКОЛА № 7 ИМЕНИ ВЛАДИМИРА НИКОЛАЕВИЧА БУЛАТОВА""",1022900530619,"муниципальное бюджетное общеобразовательное учреждение городского округа ""Город Архангельск"" ""Средняя школа № 28 имени Жореса Иванович Алфёрова""",80605,6,2025-08-22,Недостаточный
4,КРАСНОВА,АНТОНИНА,АНАТОЛЬЕВНА,2013-05-22,Ж,NaN,КРАСНОВА,ТАТЬЯНА,АРСЕНЬЕВНА,1982-10-29,Ж,0493690,26-11-20646-000005-2,1023404291459,муниципальное общеобразовательное учреждение Средняя школа с углубленным изучением отдельных предметов№ 57 Кировского района Волгограда,1213400008007,муниципальное общеобразовательное учреждение «Средняя школа № 77 Кировского района Волгограда»,30612,6,2026-03-10,Недостаточный,Ж,261113,КРАСНОВА,ТАТЬЯНА,АРСЕНЬЕВНА,1982-10-29,Ж,0493690,25-11-20646-000009-1,1023404291459,муниципальное общеобразовательное учреждение Средняя школа с углубленным изучением отдельных предметов№ 57 Кировского района Волгограда,1213400008007,муниципальное общеобразовательное учреждение «Средняя школа № 77 Кировского района Волгограда»,120609,6,2025-12-09,Недостаточный
5,ПЛАТОНОВ,АЛЕКСЕЙ,ВЛАДИМИРОВИЧ,2017-12-23,М,NaN,ГОЛУБКОВА,ОЛЬГА,МИХАЙЛОВНА,1995-06-23,Ж,0740204,25-11-40641-000105-8,1022501295409,"МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ""СРЕДНЯЯ ОБЩЕОБРАЗОВАТЕЛЬНАЯ ШКОЛА № 64 Г. ВЛАДИВОСТОКА""",1022501305804,"МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ""СРЕДНЯЯ ОБЩЕОБРАЗОВАТЕЛЬНАЯ ШКОЛА № 77 Г. ВЛАДИВОСТОКА""",80205,2,2025-08-27,Недостаточный,М,0737210,ТЯСТО,РАИСА,АЛЕКСАНДРОВНА,1995-06-23,Ж,0740204,25-11-40641-000177-5,1022501295409,"МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ""СРЕДНЯЯ ОБЩЕОБРАЗОВАТЕЛЬНАЯ ШКОЛА № 64 Г. ВЛАДИВОСТОКА""",1022501305804,"МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ""СРЕДНЯЯ ОБЩЕОБРАЗОВАТЕЛЬНАЯ ШКОЛА № 77 Г. ВЛАДИВОСТОКА""",110208,2,2025-11-26,Недостаточный

из кода ниже 46 дубликатов

In [ ]:
#atribut_x = ["gender_x", "id_doc_x", "guard_last_name_x", "guard_first_name_x"	guard_middle_name_x	guard_bdate_x	guard_gender_x	guard_id_doc_x	our_number_x	ogrn_naprav_x	name_naprav_x	ogrn_area_x	name_area_x	variant_x	class_x	test_date_x	result_x]
# atrubut_x =

In [ ]:
temp = dup[dup["test_date_x"] == dup["test_date_y"]]
temp

Empty DataFrame
Columns: [last_name, first_name, middle_name, bdate, gender_x, id_doc_x, guard_last_name_x, guard_first_name_x, guard_middle_name_x, guard_bdate_x, guard_gender_x, guard_id_doc_x, our_number_x, ogrn_naprav_x, name_naprav_x, ogrn_area_x, name_area_x, variant_x, class_x, test_date_x, result_x, gender_y, id_doc_y, guard_last_name_y, guard_first_name_y, guard_middle_name_y, guard_bdate_y, guard_gender_y, guard_id_doc_y, our_number_y, ogrn_naprav_y, name_naprav_y, ogrn_area_y, name_area_y, variant_y, class_y, test_date_y, result_y]
Index: []

In [ ]:
mask = (
    dup[["guard_last_name_x", "guard_first_name_x", "guard_middle_name_x"]].values ==
    dup[["guard_last_name_y", "guard_first_name_y", "guard_middle_name_y"]].values
).all(axis=1)

temp = dup[mask]
temp

,last_name,first_name,middle_name,bdate,gender_x,id_doc_x,guard_last_name_x,guard_first_name_x,guard_middle_name_x,guard_bdate_x,guard_gender_x,guard_id_doc_x,our_number_x,ogrn_naprav_x,name_naprav_x,ogrn_area_x,name_area_x,variant_x,class_x,test_date_x,result_x,gender_y,id_doc_y,guard_last_name_y,guard_first_name_y,guard_middle_name_y,guard_bdate_y,guard_gender_y,guard_id_doc_y,our_number_y,ogrn_naprav_y,name_naprav_y,ogrn_area_y,name_area_y,variant_y,class_y,test_date_y,result_y
0,КЛИМОВ,ДЕНИС,СЕРГЕЕВИЧ,2011-11-29,М,NaN,ЮН,МАКСИМ,ВЛАДИМИРОВИЧ,1989-11-15,М,6761430,26-11-30858-000004-9,1026500527580,Муниципальное автономное общеобразовательное учреждение средняя общеобразовательная школа № 8 имени генерал-лейтенанта В.Г. Асапова города Южно-Сахалинска,1026500529769,Муниципальное автономное общеобразовательное учреждение средняя общеобразовательная школа № 5 г. Южно-Сахалинска,10810,8,2026-01-22,недостаточный,М,-0416345,ЮН,МАКСИМ,ВЛАДИМИРОВИЧ,1989-12-15,М,6761430,25-11-30858-000068-2,1026500527580,Муниципальное автономное общеобразовательное учреждение средняя общеобразовательная школа № 8 имени генерал-лейтенанта В.Г. Асапова города Южно-Сахалинска,1026500529769,Муниципальное автономное общеобразовательное учреждение средняя общеобразовательная школа № 5 г. Южно-Сахалинска,10807,8,2025-10-09,Недостаточный
2,МИХАЙЛОВСКИЙ,АЛЕКСАНДР,АНАТОЛЬЕВИЧ,2018-10-04,М,NaN,ВИХРОВА,ЗИНАИДА,ИВАНОВНА,1991-02-19,Ж,0249074,25-11-70284-000555-3,1127747074751,Государственное бюджетное общеобразовательное учреждение города Москвы «Школа № 2000»,1115074013130,Государственное бюджетное общеобразовательное учреждение города Москвы «Школа № 2083»,110121,1,2025-11-26,Недостаточный,М,-846956,ВИХРОВА,ЗИНАИДА,ИВАНОВНА,1991-02-19,Ж,0249074,25-11-70284-000446-7,1127747074751,Государственное бюджетное общеобразовательное учреждение города Москвы «Школа № 2000»,1115074013130,Государственное бюджетное общеобразовательное учреждение города Москвы «Школа № 2083»,80109,1,2025-08-06,Недостаточный
4,КРАСНОВА,АНТОНИНА,АНАТОЛЬЕВНА,2013-05-22,Ж,NaN,КРАСНОВА,ТАТЬЯНА,АРСЕНЬЕВНА,1982-10-29,Ж,0493690,26-11-20646-000005-2,1023404291459,муниципальное общеобразовательное учреждение Средняя школа с углубленным изучением отдельных предметов№ 57 Кировского района Волгограда,1213400008007,муниципальное общеобразовательное учреждение «Средняя школа № 77 Кировского района Волгограда»,30612,6,2026-03-10,Недостаточный,Ж,261113,КРАСНОВА,ТАТЬЯНА,АРСЕНЬЕВНА,1982-10-29,Ж,0493690,25-11-20646-000009-1,1023404291459,муниципальное общеобразовательное учреждение Средняя школа с углубленным изучением отдельных предметов№ 57 Кировского района Волгограда,1213400008007,муниципальное общеобразовательное учреждение «Средняя школа № 77 Кировского района Волгограда»,120609,6,2025-12-09,Недостаточный

# альтернатива, дропнем все id = n/a

In [ ]:
df_without_na
pd.set_option("display.max_colwidth", None)
df_without_na = df_without_na.drop(["our_number", "name_naprav", "name_area"], axis=1)
df_without_na

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,ogrn_naprav,ogrn_area,variant,class,test_date,result
0,МУСЮС,АЛЕКСАНДР,NaN,2013-07-16,М,240045105,АГАФОНОВА,КЛАВДИЯ,NaN,1987-07-06,Ж,106077198701603,1022402487304,1142452001130,20611,6,2026-02-25,Недостаточный
1,СОБОЛЕВ,ЮРИЙ,ГЕННАДЬЕВИЧ,2018-01-26,М,-1236233,КАБЛИН,ВАЛЕНТИН,ГЕННАДИЕВИЧ,1991-03-15,М,1571302,1025007390077,1035004258970,120126,1,2025-12-16,Недостаточный
2,РЯБОВ,ГЕННАДИЙ,СЕРГЕЕВИЧ,2014-08-21,М,5974549,ЗАКИРОВ,БОРИС,СЕРГЕЕВИЧ,1990-03-07,М,5480835,1037816029393,1037816029547,10410,4,2026-01-20,Достаточный
3,БОРИСОВ,АНАТОЛИЙ,НИКОЛЛАЕВИЧ,2018-07-22,М,3702355,ДЖАЛОЛОВ,ЕВГЕНИЙ,АНДРАНИКОВИЧ,1992-08-23,М,402238324,1021603470360,1241600037315,20133,1,2026-02-04,Недостаточный
4,КАРПЕВИЧ,ВИКТОР,ЮРЬЕВИЧ,2019-01-18,М,0000000,ШАПРАН,ЕЛЕНА,ПАВЛОВНА,1995-01-17,Ж,0352905,1023402988234,1023402982173,60105,1,2025-06-10,достаточный
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25577,ЛАЗАРЕВ,ДЕНИС,ВЛАДИМИРОВИЧ,2015-06-28,М,2118425,ЛАЗАРЕВ,ВАЛЕРИЙ,ПЕТРОВИЧ,1991-10-06,М,402450094,1022701291250,1022701289170,60304,3,2025-07-14,Недостаточный
25578,ВИДАКОВ,МИХАИЛ,СЕРГЕЕВИЧ,2018-03-06,М,010080310,КРАСНОКУТСКИЙ,ИЛЬЯ,ВЛАДИМИРОВИЧ,1991-11-07,М,4127610,1022701286508,1022701289170,80110,1,2025-08-27,Недостаточный
25579,ТОЛОКОНУШКОВ,ЕВГЕНИЙ,ФЕДОРОВИЧ,2018-04-14,М,-N0849879,ВАСИЛЕНКО,БОРИС,СЕРГЕЕВИЧ,1978-10-02,М,2920197,1022701283208,1022701289170,80109,1,2025-08-27,Достаточный
25580,ТИХОНОВ,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,2017-09-11,М,21109201751729,МИРЗОЯН,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,1987-05-17,М,3196439,1022701291250,1022701289170,90114,1,2025-09-25,Недостаточный
25581,СОРОКИН,НИКОЛАЙ,НИКОЛАЕВИЧ,2010-01-23,М,8954785,СОРОКИН,ГРИГОРИЙ,ВЛАДИМИРОВИЧ,1978-06-24,М,845120184,1037739385056,1115074013130,50802,8,2025-05-07,Недостаточный

In [ ]:
sortik =df_without_na.sort_values(by=["last_name", "first_name", "middle_name", "id_doc", "test_date"], ascending=True)
sortik.iloc[40:60]

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,ogrn_naprav,ogrn_area,variant,class,test_date,result
17761,АБДЫКЕРИМОВ,ВИКТОР,АЛЕКСАНДРОВИЧ,2018-11-11,М,1065772,БУНИНА,ТАМАРА,ВЛАДИМИРОВНА,1990-11-14,Ж,4101532,1027200850170,1027200811384,118,1,2025-10-30,достаточный
14656,АБДЫКЕРИМОВ,ВИКТОР,NaN,2017-07-12,М,N18144647,ЗОРЬЕВА,ЛИДИЯ,NaN,1989-03-10,Ж,N18318621,1025401499705,1025401315180,100307,3,2025-10-21,Достаточный
13737,АБДЫКЕРИМОВ,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,2016-09-02,М,-N0889154,АЛЕКСАНДРОВА,НАТАЛЬЯ,ИВАНОВНА,1989-10-30,Ж,4503669,1026201087450,1026201089947,90306,3,2025-10-02,недостаточный
17262,АБДЫКЕРИМОВ,ЮРИЙ,АЛЕКСАНДРОВИЧ,2014-07-16,М,-N0714121,АЛЕКСАНДРОВА,НАТАЛЬЯ,ИВАНОВНА,1989-10-30,Ж,4503669,1026201087450,1026201089947,90506,5,2025-10-02,недостаточный
5400,АБДЮКОВА,ТАТЬЯНА,NaN,2014-04-25,Ж,0204552,АБДЮКОВА,ТАТЬЯНА,NaN,1987-02-05,Ж,0217241,1204700004321,1214700021194,60504,5,2025-07-07,Достаточный
3952,АБЕЛЯШЕВ,ВЛАДИМИР,ВЯЧЕСЛАВОВИЧ,2011-09-21,М,403723548,АБЕЛЯШЕВ,МИХАИЛ,ПЕТРОВИЧ,1975-07-14,М,402053532,1025601806537,1025600886937,90806,8,2025-09-11,Недостаточный
24057,АБЕЛЯШЕВ,ВЛАДИМИР,ВЯЧЕСЛАВОВИЧ,2011-09-21,М,403723548,МЕДНИКОВА,МАРИНА,ВАСИЛЬЕВНА,1982-04-11,Ж,831058149,1025601806537,1025600886937,120809,8,2025-12-11,Недостаточный
2448,АБЕЛЯШЕВ,РОМАН,ВЛАДИМИРОВИЧ,2017-08-22,М,5363891,ЧЕРЕДЕЕВА,ЛИДИЯ,NaN,1988-06-26,Ж,14484666,1027402544740,1027403887862,90306,3,2025-09-25,достаточный
10698,АБИДОВА,ВАЛЕНТИНА,НАУМОВНА,2018-06-05,Ж,1119552,КОРОЛЕВ,СЕРГЕЙ,СЕРГЕЕВИЧ,1990-10-14,М,2835428,1027200802694,1027200845154,90113,1,2025-09-26,достаточный
10619,АБИДОВА,ЕКАТЕРИНА,NaN,2014-07-26,Ж,№405201706,ЧОБОНОВА,ТАТЬЯНА,NaN,1994-01-28,Ж,№402196321,1022400663922,1142452001130,80505,5,2025-08-28,недостаточный
21366,АБИДОВА,НАДЕЖДА,ГРИГОРЬЕВНА,2012-08-15,Ж,-N0571389,КОНОВАЛОВА,ГАЛИНА,ВАСИЛЬЕВИЧ,1985-10-09,Ж,0436794,1035000905818,1205000119323,80705,7,2025-09-16,Недостаточный
10780,АБИЛОВА,ВАЛЕНТИНА,NaN,2015-04-16,Ж,N-2169943,АБИЛОВА,МАРИНА,NaN,1986-01-13,Ж,059727,1025004066152,1035006466593,80305,3,2025-09-16,достаточный
7868,АБИЛОВА,ЛИДИЯ,NaN,2014-08-24,Ж,N17425157,ПЕТУХОВА,ТАТЬЯНА,NaN,1987-02-22,Ж,N16275831,1025401306688,1025401315180,80505,5,2025-08-26,Достаточный
16499,АБИЛОВА,НАТАЛЬЯ,NaN,2011-07-30,Ж,N-1579861,АБИЛОВА,МАРИНА,NaN,1986-01-13,Ж,059727,1025004066152,1035006466593,80705,7,2025-09-16,достаточный
14798,АБРААМЯН,ВИКТОР,NaN,2018-05-02,М,1478672,ФЕДЯКИНА,НАДЕЖДА,NaN,1996-04-23,Ж,3070836,1246600013120,1026602336848,113,1,2025-09-20,Достаточный
947,АБРААМЯН,СЕРГЕЙ,ИЛЬИЧ,2017-07-08,М,-635972,ПОГРЕБОВА,ЛИДИЯ,NaN,1984-08-03,Ж,693860,1037816030922,1037816029547,60107,1,2025-07-08,Достаточный
2647,АБРАМЕНКОВ,ВЛАДИМИР,ВИТАЛЬЕВИЧ,2018-01-08,М,010103411,КУЛИКОВА,ЕЛЕНА,NaN,1995-07-21,Ж,1624491,1026602956533,1026605763645,110122,1,2025-11-15,Недостаточный
3759,АБРАМЕНКОВ,ВЛАДИМИР,ВИТАЛЬЕВИЧ,2018-01-08,М,20801201851575,КУЛИКОВА,ЕКАТЕРИНА,NaN,1995-07-21,Ж,1624491,1026602951231,1026605241541,60106,1,2025-07-03,Недостаточный
13432,АБРАМЕНКОВ,ГЕННАДИЙ,NaN,2018-09-05,М,0424018,АБРАМЕНКОВ,ВИКТОР,NaN,1992-10-29,М,0648005,1022401944883,1142452001130,50103,1,2025-05-22,достаточный
1779,АБРАМОВ,АЛЕКСАНДР,ВАСИЛЬЕВИЧ,2015-03-30,М,1025920,ЧАДЕРИН,МИХАИЛ,NaN,1979-06-02,М,3486594,1022501905238,1022501912564,110508,5,2025-11-26,Недостаточный

In [72]:
df_without_na.describe()

        ogrn_naprav     ogrn_area
count  2.558200e+04  2.558200e+04
mean   1.105069e+12  1.050165e+12
std    2.046097e+12  5.330424e+10
min    1.020101e+12  1.020101e+12
25%    1.024701e+12  1.025203e+12
50%    1.027102e+12  1.027403e+12
75%    1.035006e+12  1.035404e+12
max    3.210571e+14  1.241600e+12

In [ ]:
counts = df_id_full["our_number"].value_counts()
counts

our_number
26-11-60078-000038-4    1
25-11-70122-000036-6    1
26-11-70285-000004-4    1
26-11-70046-000006-7    1
25-11-60108-000020-9    1
                       ..
25-11-70289-000015-7    1
25-11-70289-000009-8    1
25-11-70289-000014-8    1
25-11-70289-000019-9    1
25-11-70284-000634-1    1
Name: count, Length: 25628, dtype: int64

In [ ]:
df_without_na[["bdate", "test_date"]] = df_without_na[["bdate", "test_date"]].apply(pd.to_datetime)
df_without_na.info()

<class 'pandas.DataFrame'>
RangeIndex: 25582 entries, 0 to 25581
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   last_name          25582 non-null  str
 1   first_name         25582 non-null  str
 2   middle_name        21115 non-null  str
 3   bdate              25582 non-null  datetime64[us]
 4   gender             25582 non-null  str
 5   id_doc             25582 non-null  str
 6   guard_last_name    25582 non-null  str
 7   guard_first_name   25582 non-null  str
 8   guard_middle_name  18199 non-null  str
 9   guard_bdate        25582 non-null  str
 10  guard_gender       25582 non-null  str
 11  guard_id_doc       25509 non-null  str
 12  ogrn_naprav        25582 non-null  int64
 13  ogrn_area          25582 non-null  int64
 14  variant            25582 non-null  str
 15  class              25582 non-null  str
 16  test_date          25582 non-null  datetime64[us]
 17  result             25582 non-null  str
dtypes: datetime64[us](2), int64(2), str(14)
memory usage: 3.5 MB

## аномалия. дата проведения теста раньше даты рождения.

In [ ]:

errors = df_without_na[df_without_na["test_date"] < df_without_na["bdate"]]
print(errors)

     last_name first_name middle_name      bdate gender    id_doc  \
2165   ЛУКОНИН     МИХАИЛ         NaN 2025-09-18      М  13653549

     guard_last_name guard_first_name guard_middle_name guard_bdate  \
2165         ЛУКОНИН         АНАТОЛИЙ        НИКОЛАЕВИЧ  1982-06-13

     guard_gender guard_id_doc    ogrn_naprav      ogrn_area variant class  \
2165            М   4223444657  1183668037189  1193668014737   90706     7

      test_date         result
2165 2025-09-16  Недостаточный

In [76]:
df_without_na = df_without_na.drop(df.index[2165])

## дубликаты 
поиск и удаление

In [77]:
dup2 = df_without_na[df_without_na.duplicated()]
dup2

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,ogrn_naprav,ogrn_area,variant,class,test_date,result
803,КАМНЕВ,АЛЕКСАНДР,NaN,2012-03-23,М,2859490,МАЗУРОВА,ЗОЯ,NaN,1990-03-21,Ж,2859334,1026200780935,1026200779384,120809,8,2025-12-04,Недостаточный
1201,ЖИГАЛОВ,ЕВГЕНИЙ,НИКОЛАЕВИЧ,2015-07-14,М,№2276319,ТЕШАЕВА,ЕКАТЕРИНА,АЛЕКСАНДРОВНА,1992-09-19,Ж,19403084235,1033301002525,1033301002525,20311,3,2026-02-19,Недостаточный
1490,ЛУТАЙ,ИГОРЬ,NaN,2015-08-08,М,№2585647,ЖУРАВЛЕВА,ТАТЬЯНА,NaN,1983-07-28,Ж,№5304,1116330004185,1116330004185,50104,1,2025-05-28,недостаточный
1492,ЛУТАЙ,ИГОРЬ,NaN,2015-08-08,М,№2585647,ЖУРАВЛЕВА,ТАТЬЯНА,NaN,1983-07-28,Ж,№5304,1116330004185,1116330004185,50104,1,2025-05-28,недостаточный
1623,КНЯЗЕВ,ВАЛЕНТИН,NaN,2016-11-07,М,404659670,ЯКОВЛЕВА,МАРИЯ,АЛЕКСЕЕВНА,1988-01-15,Ж,404617155,1021603275561,1021603273009,90113,1,2025-07-08,Достаточный
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24999,ЗАГИДОВ,ВЛАДИМИР,ЯРУЛЛОВИЧ,2018-09-03,М,-№0610241,ЗВОНЦОВА,АЛЬФИЯ,ЯХИЕВНА,1991-02-10,Ж,5614133,1024900971182,1024900972183,80109,1,2025-08-25,Недостаточный
25014,ОСМОЛОВСКИЙ,АЛЕКСАНДР,NaN,2018-10-19,М,2501278,МИТРОШИНА,ТАТЬЯНА,NaN,1989-02-17,Ж,2569398,1021602837552,1021602837552,105,1,2025-06-25,достаточный
25209,ЗУБКОВ,АНДРЕЙ,ВАСИЛЬЕВИЧ,2018-12-04,М,№3895225,БУКЛИКОВА,ТАТЬЯНА,ВИКТОРОВНА,1984-08-09,Ж,№405980209,1027739814178,1027739814178,80110,1,2025-08-20,Недостаточный
25210,СТРЕЛКОВ,АНАТОЛИЙ,NaN,2018-03-06,М,1438333,ЗЫКОВ,АЛЕКСАНДР,NaN,1988-01-04,М,4475756,1024900961590,1024900972183,80110,1,2025-08-25,Недостаточный
25426,ЛЕБЕДЕВ,ВАСИЛИЙ,ПЕТРОВИЧ,2018-09-11,М,№4447239,ЛЕБЕДЕВ,ВИКТОР,ВИКТОРОВИЧ,1994-09-09,М,83№0030902,1022304013984,1022304014490,80110,1,2025-08-27,Достаточный

In [ ]:
counts = df_id_full["result"].value_counts()
counts

result
Недостаточный    11160
Достаточный      10098
достаточный       2144
недостаточный     1995
ДОСТАТОЧНЫЙ        171
НЕДОСТАТОЧНЫЙ       51
НЕдостаточный        9
Name: count, dtype: int64

In [ ]:
df_without_na["result"] = df_without_na["result"].str.upper()
df_without_na

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,ogrn_naprav,ogrn_area,variant,class,test_date,result
0,МУСЮС,АЛЕКСАНДР,NaN,2013-07-16,М,240045105,АГАФОНОВА,КЛАВДИЯ,NaN,1987-07-06,Ж,106077198701603,1022402487304,1142452001130,20611,6,2026-02-25,НЕДОСТАТОЧНЫЙ
1,СОБОЛЕВ,ЮРИЙ,ГЕННАДЬЕВИЧ,2018-01-26,М,-1236233,КАБЛИН,ВАЛЕНТИН,ГЕННАДИЕВИЧ,1991-03-15,М,1571302,1025007390077,1035004258970,120126,1,2025-12-16,НЕДОСТАТОЧНЫЙ
2,РЯБОВ,ГЕННАДИЙ,СЕРГЕЕВИЧ,2014-08-21,М,5974549,ЗАКИРОВ,БОРИС,СЕРГЕЕВИЧ,1990-03-07,М,5480835,1037816029393,1037816029547,10410,4,2026-01-20,ДОСТАТОЧНЫЙ
3,БОРИСОВ,АНАТОЛИЙ,НИКОЛЛАЕВИЧ,2018-07-22,М,3702355,ДЖАЛОЛОВ,ЕВГЕНИЙ,АНДРАНИКОВИЧ,1992-08-23,М,402238324,1021603470360,1241600037315,20133,1,2026-02-04,НЕДОСТАТОЧНЫЙ
4,КАРПЕВИЧ,ВИКТОР,ЮРЬЕВИЧ,2019-01-18,М,0000000,ШАПРАН,ЕЛЕНА,ПАВЛОВНА,1995-01-17,Ж,0352905,1023402988234,1023402982173,60105,1,2025-06-10,ДОСТАТОЧНЫЙ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25577,ЛАЗАРЕВ,ДЕНИС,ВЛАДИМИРОВИЧ,2015-06-28,М,2118425,ЛАЗАРЕВ,ВАЛЕРИЙ,ПЕТРОВИЧ,1991-10-06,М,402450094,1022701291250,1022701289170,60304,3,2025-07-14,НЕДОСТАТОЧНЫЙ
25578,ВИДАКОВ,МИХАИЛ,СЕРГЕЕВИЧ,2018-03-06,М,010080310,КРАСНОКУТСКИЙ,ИЛЬЯ,ВЛАДИМИРОВИЧ,1991-11-07,М,4127610,1022701286508,1022701289170,80110,1,2025-08-27,НЕДОСТАТОЧНЫЙ
25579,ТОЛОКОНУШКОВ,ЕВГЕНИЙ,ФЕДОРОВИЧ,2018-04-14,М,-N0849879,ВАСИЛЕНКО,БОРИС,СЕРГЕЕВИЧ,1978-10-02,М,2920197,1022701283208,1022701289170,80109,1,2025-08-27,ДОСТАТОЧНЫЙ
25580,ТИХОНОВ,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,2017-09-11,М,21109201751729,МИРЗОЯН,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,1987-05-17,М,3196439,1022701291250,1022701289170,90114,1,2025-09-25,НЕДОСТАТОЧНЫЙ
25581,СОРОКИН,НИКОЛАЙ,НИКОЛАЕВИЧ,2010-01-23,М,8954785,СОРОКИН,ГРИГОРИЙ,ВЛАДИМИРОВИЧ,1978-06-24,М,845120184,1037739385056,1115074013130,50802,8,2025-05-07,НЕДОСТАТОЧНЫЙ

In [ ]:
df_without_na = df_without_na.drop_duplicates(keep="last")

In [ ]:
df_without_na.to_csv("data/without_duplicates.csv")

In [ ]:
counts = df_id_full["id_doc"].value_counts()
counts

id_doc
0594160           9
0682253           8
404331516         8
0682384           6
0682366           6
                 ..
3984093           1
4508342           1
5540615           1
-N0849879         1
21109201751729    1
Name: count, Length: 21926, dtype: int64

In [ ]:
df_without_na[df_without_na["id_doc"] == "0594160"]
# df_without_na[df_without_na["id_doc"] == "0682253"]
# df_without_na[df_without_na["id_doc"] == "404331516"]   #здесь один и тот же человек но с другим отчеством, однако test_date во всех 8 записях один

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,ogrn_naprav,ogrn_area,variant,class,test_date,result
3008,ЛУКИНЫХ,ВЯЧЕСЛАВ,КОНСТАНТИНОВИЧ,2013-01-01,М,0594160,ЛОЗОВАЯ,НИНА,ВАСИЛЬЕВНА,1984-01-09,Ж,0594160,1023101683406,1023101670393,60704,7,2025-07-25,НЕДОСТАТОЧНЫЙ
6885,СОЛОВЬЕВА,АННА,СЕРГЕЕВНА,2010-08-29,Ж,0594160,ЛОЗОВАЯ,НИНА,ВАСИЛЬЕВНА,1984-01-09,Ж,0594160,1023101683406,1023101670393,60904,9,2025-07-25,НЕДОСТАТОЧНЫЙ
7265,СОЛОВЬЕВА,АННА,СЕРГЕЕВНА,2010-08-29,Ж,0594160,ЛОЗОВАЯ,НИНА,ВАСИЛЬЕВНА,1984-01-09,Ж,0594160,1023101683406,1023101670393,30712,7,2026-03-12,НЕДОСТАТОЧНЫЙ
18909,СОЛОВЬЕВА,АННА,СЕРГЕЕВНА,2010-08-29,Ж,0594160,ЛОЗОВАЯ,НИНА,ВАСИЛЬЕВНА,1984-01-09,Ж,0594160,1023101683406,1023101670393,120909,9,2025-12-12,НЕДОСТАТОЧНЫЙ
22759,ЛУКИНЫХ,АНАТОЛИЙ,КОНСТАНТИНОВИЧ,2015-07-20,М,0594160,ЛОЗОВАЯ,НИНА,ВАСИЛЬЕВНА,1984-01-09,Ж,0594160,1023101683406,1023101670393,60404,4,2025-07-25,НЕДОСТАТОЧНЫЙ
22776,ЛУКИНЫХ,ВЯЧЕСЛАВ,КОНСТАНТИНОВИЧ,2013-01-01,М,0594160,ЛОЗОВАЯ,НИНА,ВАСИЛЬЕВНА,1984-01-09,Ж,0594160,1023101683406,1023101670393,120709,7,2025-12-12,НЕДОСТАТОЧНЫЙ
22783,ЛУКИНЫХ,АНАТОЛИЙ,КОНСТАНТИНОВИЧ,2015-07-20,М,0594160,ЛОЗОВАЯ,НИНА,ВАСИЛЬЕВНА,1984-01-09,Ж,0594160,1023101683406,1023101670393,120409,4,2025-12-12,НЕДОСТАТОЧНЫЙ
23102,ЛУКИНЫХ,АНАТОЛИЙ,КОНСТАНТИНОВИЧ,2015-07-20,М,0594160,ЛОЗОВАЯ,НИНА,ВАСИЛЬЕВНА,1984-01-09,Ж,0594160,1023101683406,1023101670393,30212,2,2026-03-12,НЕДОСТАТОЧНЫЙ
23106,ЛУКИНЫХ,ВЯЧЕСЛАВ,КОНСТАНТИНОВИЧ,2013-01-01,М,0594160,ЛОЗОВАЯ,НИНА,ВАСИЛЬЕВНА,1984-01-09,Ж,0594160,1023101683406,1023101670393,30512,5,2026-03-12,НЕДОСТАТОЧНЫЙ

In [ ]:
counts = df_id_full["variant"].value_counts()
counts

variant
80109         1742
80110         1485
90113         1234
90114          785
100117         743
              ...
202133           1
2500700150       1
211              1
0                1
неявился         1
Name: count, Length: 640, dtype: int64

АНОМАЛИЯ ВЫШЕ!
ну или просто хз (я про 0 и про неявился)

In [ ]:
counts = df_id_full["class"].value_counts()
counts

class
1      12306
5       1952
2       1839
3       1803
4       1762
6       1570
7       1534
8       1354
9        972
10       388
11       147
2-5        1
Name: count, dtype: int64

2-5 - что это ваще удалить